# Generated by Django 6.0.3 on 2026-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='food', max_length=50),
            preserve_default=False,
        ),
    ]
